# Generated by Django 5.1 on 2026-09-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('monthly_income', models.FloatField(help_text='Monthly income in Naira')),
                ('loan_amount', models.FloatField()),
                ('loan_tenure', models.IntegerField(default=12, help_text='Months')),
                ('credit_score', models.IntegerField(help_text='300-850')),
                ('employment_years', models.IntegerField()),
                ('existing_loans', models.IntegerField(default=0)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=20)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review')], default='MANUAL_REVIEW', max_length=20)),
                ('risk_score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
