# Generated by Django 5.1 on 2026-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='photo',
            field=models.ImageField(blank=True, help_text='Applicant photo', null=True, upload_to='applicants/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_tenure',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.FloatField(),
        ),
    ]
