# Generated by Django 5.1 on 2026-09-25 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loanapplication_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ai_decision',
            field=models.CharField(default='MANUAL_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ceo_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ceo_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending CEO Approval'), ('APPROVED', 'Approved by CEO'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CEO', 'CEO - Global Approver'), ('MANAGER', 'Branch Manager'), ('OFFICER', 'Loan Officer')], default='OFFICER', max_length=20)),
                ('branch', models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
