# Generated by Django 5.2.5 on 2026-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO - Global Approver'), ('ADMIN', 'Admin'), ('MANAGER', 'Branch Manager'), ('OFFICER', 'Loan Officer'), ('MIS', 'MIS')], default='OFFICER', max_length=20),
        ),
    ]
