# Generated by Django 5.2.5 on 2026-09-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_branch_client_email_client_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='ai_decision',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='ceo_approved',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='ceo_comment',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='reason',
        ),
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.client'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.CharField(blank=True, default='Business', max_length=200),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('ENUGU', 'ENUGU'), ('KANO', 'KANO')], default='LAGOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
    ]
