# Generated by Django 5.2.5 on 2026-09-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_client_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('ENUGU', 'ENUGU'), ('KANO', 'KANO')], default='LAGOS', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('ENUGU', 'ENUGU'), ('KANO', 'KANO')], default='LAGOS', max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='core.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('ENUGU', 'ENUGU'), ('KANO', 'KANO')], default='LAGOS', max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.loanapplication')),
            ],
        ),
    ]
