# Generated by Django 5.2.5 on 2026-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_branchsaving_loandefault_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandefault',
            name='id_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loandefault',
            name='reason',
            field=models.CharField(default='You did not Pay your Repayment today', max_length=200),
        ),
    ]
