# Generated by Django 6.0.3 on 2026-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loanapplication_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsaving',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(default=650),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_years',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=50000),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='loandefault',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OFFICER', 'Officer'), ('CREDIT_OFFICER', 'Credit Officer'), ('MIS', 'MIS Officer')], default='OFFICER', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='branch',
            field=models.CharField(choices=[('LAGOS', 'Lagos - HQ'), ('ABUJA', 'Abuja'), ('PH', 'Port Harcourt'), ('KANO', 'Kano'), ('IBADAN', 'Ibadan'), ('ENUGU', 'Enugu')], default='LAGOS', max_length=20),
        ),
    ]
