# Generated by Django 5.2.5 on 2026-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW'), ('DISBURSED', 'DISBURSED')], default='PENDING', max_length=20),
        ),
    ]
