# Generated by Django 5.2.5 on 2026-09-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_loanapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_id_code', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(default='LAGOS', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('weekly_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_stage', models.CharField(choices=[('FIRST', 'First Loan'), ('SECOND', 'Second Loan'), ('THIRD', 'Third+ Loan'), ('SETTLED', 'Settled'), ('DEFAULT', 'Default')], default='FIRST', max_length=20)),
                ('weekly_repayment_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Loan Repayment per Week')),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repayment_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly Loan Field')),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
