# Generated by Django 5.2.5 on 2026-09-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fieldcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcollection',
            name='loan_stage',
            field=models.CharField(default='FIRST', help_text='e.g. FIRST, SECOND, 4th, 5th, 10th', max_length=100),
        ),
    ]
