# Generated by Django 5.2.5 on 2026-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_fieldcollection_loan_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcollection',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('DEFAULT', 'DEFAULT'), ('PARTIAL', 'PARTIAL')], default='DEFAULT', max_length=10),
        ),
    ]
