# Generated by Django 5.2.5 on 2026-09-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fieldcollection_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcollection',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('DEFAULT', 'DEFAULT'), ('PARTIAL', 'PARTIAL')], max_length=10),
        ),
    ]
