# Generated by Django 5.2.5 on 2026-09-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_fieldcollection_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekly_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('loan_application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loanapplication')),
            ],
        ),
    ]
