# Generated by Django 5.2.5 on 2026-09-28 10:12

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('license_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(default=datetime.date(2026, 10, 28))),
                ('max_users', models.IntegerField(default=10)),
                ('license_type', models.CharField(choices=[('TRIAL', 'Trial'), ('ANNUAL', 'Annual'), ('OUTRIGHT', 'Outright')], default='ANNUAL', max_length=20)),
            ],
        ),
    ]
